import { ChatBriefViewResponse } from '@api/lib';

export const chats: ChatBriefViewResponse[] = [
  {
    id: 'chat001',
    chatName: undefined,
    type: 'Private',
    participants: [
      {
        id: 'user001',
        chatId: 'chat001',
        username: 'user1',
        fullname: 'John Doe',
        role: 'Participant',
        joined: new Date('2023-05-01T12:00:00Z'),
      },
      {
        id: 'user002',
        chatId: 'chat001',
        username: 'Piter Parcker',
        fullname: 'Jane Smith',
        role: 'Participant',
        joined: new Date('2023-05-01T12:05:00Z'),
      },
    ],
    lastMessage: {
      id: 'msg001',
      authorUserName: 'user1',
      authorFullName: 'John Doe',
      content: 'I love making these amazing layouts ...',
      timestamp: new Date('2023-05-12T12:05:00Z'),
    },
  },
  {
    id: 'chat002',
    chatName: undefined,
    type: 'Private',
    participants: [
      {
        id: 'user001',
        chatId: 'chat001',
        username: 'user1',
        fullname: 'John Doe',
        role: 'Participant',
        joined: new Date('2023-05-01T12:00:00Z'),
      },
      {
        id: 'user002',
        chatId: 'chat001',
        username: 'Andrew Lincoln',
        fullname: 'Jane Smith',
        role: 'Participant',
        joined: new Date('2023-05-01T12:05:00Z'),
      },
    ],
    lastMessage: {
      id: 'msg001',
      authorUserName: 'user1',
      authorFullName: 'John Doe',
      content: 'Hello Andrew!',
      timestamp: new Date('2023-05-22T12:05:00Z'),
    },
  },
  {
    id: 'chat003',
    chatName: undefined,
    type: 'Private',
    participants: [
      {
        id: 'user001',
        chatId: 'chat001',
        username: 'user1',
        fullname: 'John Doe',
        role: 'Participant',
        joined: new Date('2023-05-01T12:00:00Z'),
      },
      {
        id: 'user002',
        chatId: 'chat001',
        username: 'Robert Polson',
        fullname: 'Jane Smith',
        role: 'Participant',
        joined: new Date('2023-05-01T12:05:00Z'),
      },
    ],
    lastMessage: {
      id: 'msg001',
      authorUserName: 'user1',
      authorFullName: 'John Doe',
      content: 'His name is Robert Polson!',
      timestamp: new Date('2023-05-22T12:05:00Z'),
    },
  },
  {
    id: 'chat004',
    chatName: undefined,
    type: 'Private',
    participants: [
      {
        id: 'user001',
        chatId: 'chat001',
        username: 'user1',
        fullname: 'John Doe',
        role: 'Participant',
        joined: new Date('2023-05-01T12:00:00Z'),
      },
      {
        id: 'user002',
        chatId: 'chat001',
        username: 'Norman Reedus',
        fullname: 'Jane Smith',
        role: 'Participant',
        joined: new Date('2023-05-01T12:05:00Z'),
      },
    ],
    lastMessage: {
      id: 'msg001',
      authorUserName: 'user1',
      authorFullName: 'John Doe',
      content: 'Hello Norman!',
      timestamp: new Date('2023-05-02T12:05:00Z'),
    },
  },
  {
    id: 'group002',
    chatName: 'Private chat',
    type: 'Private',
    participants: [
      {
        id: 'user001',
        chatId: 'chat002',
        username: 'user1',
        fullname: 'John Doe',
        role: 'Participant',
        joined: new Date('2023-05-02T12:00:00Z'),
      },
      {
        id: 'user003',
        chatId: 'chat002',
        username: 'Habib',
        fullname: 'Bob Johnson',
        role: 'Participant',
        joined: new Date('2023-05-02T12:05:00Z'),
      },
      {
        id: 'user003',
        chatId: 'chat002',
        username: 'Amateur',
        fullname: 'Bob Johnson',
        role: 'Participant',
        joined: new Date('2023-05-02T12:05:00Z'),
      },
      {
        id: 'user003',
        chatId: 'chat002',
        username: 'Pro100user',
        fullname: 'Bob Johnson',
        role: 'Participant',
        joined: new Date('2023-05-02T12:05:00Z'),
      },
    ],
    lastMessage: {
      id: 'msg002',
      authorUserName: 'Joe',
      authorFullName: 'Bob Johnson',
      content: "Hey John, what's up?",
      timestamp: new Date('2022-05-02T12:10:00Z'),
    },
  },
  {
    id: 'group003',
    chatName: 'Suicide squad',
    type: 'Private',
    participants: [
      {
        id: 'user001',
        chatId: 'chat002',
        username: 'user1',
        fullname: 'John Doe',
        role: 'Participant',
        joined: new Date('2023-05-02T12:00:00Z'),
      },
      {
        id: 'user003',
        chatId: 'chat002',
        username: 'Habib',
        fullname: 'Bob Johnson',
        role: 'Participant',
        joined: new Date('2023-05-02T12:05:00Z'),
      },
      {
        id: 'user003',
        chatId: 'chat002',
        username: 'Amateur',
        fullname: 'Bob Johnson',
        role: 'Participant',
        joined: new Date('2023-04-02T12:05:00Z'),
      },
      {
        id: 'user003',
        chatId: 'chat002',
        username: 'Pro100user',
        fullname: 'Bob Johnson',
        role: 'Participant',
        joined: new Date('2023-05-02T12:05:00Z'),
      },
    ],
    lastMessage: {
      id: 'msg002',
      authorUserName: 'Joker',
      authorFullName: 'Bob Johnson',
      content: 'Question... Will you die for me?',
      timestamp: new Date('2022-06-22T12:10:00Z'),
    },
  },
]; //temporary variables

export const currentChat: ChatBriefViewResponse = {
  id: 'chat001',
  chatName: undefined,
  type: 'Private',
  participants: [
    {
      id: 'user001',
      chatId: 'chat001',
      username: 'user1',
      fullname: 'John Doe',
      role: 'Participant',
      joined: new Date('2023-05-01T12:00:00Z'),
    },
    {
      id: 'user002',
      chatId: 'chat001',
      username: 'user2',
      fullname: 'Jane Smith',
      role: 'Participant',
      joined: new Date('2023-05-01T12:05:00Z'),
    },
  ],
  lastMessage: {
    id: 'msg001',
    authorUserName: 'user1',
    authorFullName: 'John Doe',
    content: 'Hello Jane, how are you?',
    timestamp: new Date(),
  },
}; //temporary variables
