/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddUserToGroupChatRequest
 */
export interface AddUserToGroupChatRequest {
  /**
   * Id of the user to be added.
   * @type {string}
   * @memberof AddUserToGroupChatRequest
   */
  userId: string;
}

/**
 * Check if a given object implements the AddUserToGroupChatRequest interface.
 */
export function instanceOfAddUserToGroupChatRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'userId' in value;

  return isInstance;
}

export function AddUserToGroupChatRequestFromJSON(
  json: any,
): AddUserToGroupChatRequest {
  return AddUserToGroupChatRequestFromJSONTyped(json, false);
}

export function AddUserToGroupChatRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddUserToGroupChatRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: json['userId'],
  };
}

export function AddUserToGroupChatRequestToJSON(
  value?: AddUserToGroupChatRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userId: value.userId,
  };
}
