/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ApiChatsPrivatePost400Response
 */
export interface ApiChatsPrivatePost400Response {
  /**
   *
   * @type {string}
   * @memberof ApiChatsPrivatePost400Response
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof ApiChatsPrivatePost400Response
   */
  title?: string;
  /**
   *
   * @type {number}
   * @memberof ApiChatsPrivatePost400Response
   */
  status?: number;
  /**
   *
   * @type {string}
   * @memberof ApiChatsPrivatePost400Response
   */
  detail?: string;
  /**
   *
   * @type {string}
   * @memberof ApiChatsPrivatePost400Response
   */
  traceId?: string;
  /**
   *
   * @type {{ [key: string]: Array<string>; }}
   * @memberof ApiChatsPrivatePost400Response
   */
  errors?: { [key: string]: Array<string> };
}

/**
 * Check if a given object implements the ApiChatsPrivatePost400Response interface.
 */
export function instanceOfApiChatsPrivatePost400Response(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ApiChatsPrivatePost400ResponseFromJSON(
  json: any,
): ApiChatsPrivatePost400Response {
  return ApiChatsPrivatePost400ResponseFromJSONTyped(json, false);
}

export function ApiChatsPrivatePost400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApiChatsPrivatePost400Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, 'type') ? undefined : json['type'],
    title: !exists(json, 'title') ? undefined : json['title'],
    status: !exists(json, 'status') ? undefined : json['status'],
    detail: !exists(json, 'detail') ? undefined : json['detail'],
    traceId: !exists(json, 'traceId') ? undefined : json['traceId'],
    errors: !exists(json, 'errors') ? undefined : json['errors'],
  };
}

export function ApiChatsPrivatePost400ResponseToJSON(
  value?: ApiChatsPrivatePost400Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    title: value.title,
    status: value.status,
    detail: value.detail,
    traceId: value.traceId,
    errors: value.errors,
  };
}
