/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthLoginPost401Response
 */
export interface AuthLoginPost401Response {
  /**
   *
   * @type {string}
   * @memberof AuthLoginPost401Response
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof AuthLoginPost401Response
   */
  title?: string;
  /**
   *
   * @type {number}
   * @memberof AuthLoginPost401Response
   */
  status?: number;
  /**
   *
   * @type {string}
   * @memberof AuthLoginPost401Response
   */
  detail?: string;
  /**
   *
   * @type {string}
   * @memberof AuthLoginPost401Response
   */
  traceId?: string;
}

/**
 * Check if a given object implements the AuthLoginPost401Response interface.
 */
export function instanceOfAuthLoginPost401Response(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AuthLoginPost401ResponseFromJSON(
  json: any,
): AuthLoginPost401Response {
  return AuthLoginPost401ResponseFromJSONTyped(json, false);
}

export function AuthLoginPost401ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuthLoginPost401Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, 'type') ? undefined : json['type'],
    title: !exists(json, 'title') ? undefined : json['title'],
    status: !exists(json, 'status') ? undefined : json['status'],
    detail: !exists(json, 'detail') ? undefined : json['detail'],
    traceId: !exists(json, 'traceId') ? undefined : json['traceId'],
  };
}

export function AuthLoginPost401ResponseToJSON(
  value?: AuthLoginPost401Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    title: value.title,
    status: value.status,
    detail: value.detail,
    traceId: value.traceId,
  };
}
