/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ChatTypeFilter = {
  All: 'All',
  Private: 'Private',
} as const;
export type ChatTypeFilter =
  (typeof ChatTypeFilter)[keyof typeof ChatTypeFilter];

export function ChatTypeFilterFromJSON(json: any): ChatTypeFilter {
  return ChatTypeFilterFromJSONTyped(json, false);
}

export function ChatTypeFilterFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChatTypeFilter {
  return json as ChatTypeFilter;
}

export function ChatTypeFilterToJSON(value?: ChatTypeFilter | null): any {
  return value as any;
}
