/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ChatUserMinimalNoChatResponse
 */
export interface ChatUserMinimalNoChatResponse {
  /**
   *
   * @type {string}
   * @memberof ChatUserMinimalNoChatResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ChatUserMinimalNoChatResponse
   */
  name?: string | null;
}

/**
 * Check if a given object implements the ChatUserMinimalNoChatResponse interface.
 */
export function instanceOfChatUserMinimalNoChatResponse(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function ChatUserMinimalNoChatResponseFromJSON(
  json: any,
): ChatUserMinimalNoChatResponse {
  return ChatUserMinimalNoChatResponseFromJSONTyped(json, false);
}

export function ChatUserMinimalNoChatResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChatUserMinimalNoChatResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
  };
}

export function ChatUserMinimalNoChatResponseToJSON(
  value?: ChatUserMinimalNoChatResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
  };
}
