/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateGroupChatRequest
 */
export interface CreateGroupChatRequest {
  /**
   *
   * @type {Array<string>}
   * @memberof CreateGroupChatRequest
   */
  userIds?: Array<string> | null;
}

/**
 * Check if a given object implements the CreateGroupChatRequest interface.
 */
export function instanceOfCreateGroupChatRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CreateGroupChatRequestFromJSON(
  json: any,
): CreateGroupChatRequest {
  return CreateGroupChatRequestFromJSONTyped(json, false);
}

export function CreateGroupChatRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateGroupChatRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userIds: !exists(json, 'userIds') ? undefined : json['userIds'],
  };
}

export function CreateGroupChatRequestToJSON(
  value?: CreateGroupChatRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userIds: value.userIds,
  };
}
