/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ForgotPassModel
 */
export interface ForgotPassModel {
  /**
   *
   * @type {string}
   * @memberof ForgotPassModel
   */
  email: string;
}

/**
 * Check if a given object implements the ForgotPassModel interface.
 */
export function instanceOfForgotPassModel(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'email' in value;

  return isInstance;
}

export function ForgotPassModelFromJSON(json: any): ForgotPassModel {
  return ForgotPassModelFromJSONTyped(json, false);
}

export function ForgotPassModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ForgotPassModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
  };
}

export function ForgotPassModelToJSON(value?: ForgotPassModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
  };
}
