/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface JwtResult
 */
export interface JwtResult {
  /**
   *
   * @type {string}
   * @memberof JwtResult
   */
  token: string;
  /**
   *
   * @type {Date}
   * @memberof JwtResult
   */
  expiryDate: Date;
}

/**
 * Check if a given object implements the JwtResult interface.
 */
export function instanceOfJwtResult(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'token' in value;
  isInstance = isInstance && 'expiryDate' in value;

  return isInstance;
}

export function JwtResultFromJSON(json: any): JwtResult {
  return JwtResultFromJSONTyped(json, false);
}

export function JwtResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): JwtResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    token: json['token'],
    expiryDate: new Date(json['expiryDate']),
  };
}

export function JwtResultToJSON(value?: JwtResult | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    token: value.token,
    expiryDate: value.expiryDate.toISOString(),
  };
}
