/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LoginModel
 */
export interface LoginModel {
  /**
   *
   * @type {string}
   * @memberof LoginModel
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof LoginModel
   */
  password: string;
}

/**
 * Check if a given object implements the LoginModel interface.
 */
export function instanceOfLoginModel(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'username' in value;
  isInstance = isInstance && 'password' in value;

  return isInstance;
}

export function LoginModelFromJSON(json: any): LoginModel {
  return LoginModelFromJSONTyped(json, false);
}

export function LoginModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoginModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: json['username'],
    password: json['password'],
  };
}

export function LoginModelToJSON(value?: LoginModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
    password: value.password,
  };
}
