/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MessageReplyResponse
 */
export interface MessageReplyResponse {
  /**
   *
   * @type {string}
   * @memberof MessageReplyResponse
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof MessageReplyResponse
   */
  username?: string | null;
  /**
   *
   * @type {string}
   * @memberof MessageReplyResponse
   */
  content?: string | null;
  /**
   *
   * @type {Date}
   * @memberof MessageReplyResponse
   */
  timestamp?: Date;
}

/**
 * Check if a given object implements the MessageReplyResponse interface.
 */
export function instanceOfMessageReplyResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function MessageReplyResponseFromJSON(json: any): MessageReplyResponse {
  return MessageReplyResponseFromJSONTyped(json, false);
}

export function MessageReplyResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MessageReplyResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    username: !exists(json, 'username') ? undefined : json['username'],
    content: !exists(json, 'content') ? undefined : json['content'],
    timestamp: !exists(json, 'timestamp')
      ? undefined
      : new Date(json['timestamp']),
  };
}

export function MessageReplyResponseToJSON(
  value?: MessageReplyResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    username: value.username,
    content: value.content,
    timestamp:
      value.timestamp === undefined ? undefined : value.timestamp.toISOString(),
  };
}
