/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const MessageType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
export type MessageType = (typeof MessageType)[keyof typeof MessageType];

export function MessageTypeFromJSON(json: any): MessageType {
  return MessageTypeFromJSONTyped(json, false);
}

export function MessageTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MessageType {
  return json as MessageType;
}

export function MessageTypeToJSON(value?: MessageType | null): any {
  return value as any;
}
