/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RegisterModel
 */
export interface RegisterModel {
  /**
   *
   * @type {string}
   * @memberof RegisterModel
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof RegisterModel
   */
  fullName: string;
  /**
   *
   * @type {string}
   * @memberof RegisterModel
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RegisterModel
   */
  password: string;
}

/**
 * Check if a given object implements the RegisterModel interface.
 */
export function instanceOfRegisterModel(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'username' in value;
  isInstance = isInstance && 'fullName' in value;
  isInstance = isInstance && 'email' in value;
  isInstance = isInstance && 'password' in value;

  return isInstance;
}

export function RegisterModelFromJSON(json: any): RegisterModel {
  return RegisterModelFromJSONTyped(json, false);
}

export function RegisterModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: json['username'],
    fullName: json['fullName'],
    email: json['email'],
    password: json['password'],
  };
}

export function RegisterModelToJSON(value?: RegisterModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
    fullName: value.fullName,
    email: value.email,
    password: value.password,
  };
}
