/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResetForgotPassModel
 */
export interface ResetForgotPassModel {
  /**
   *
   * @type {string}
   * @memberof ResetForgotPassModel
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof ResetForgotPassModel
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof ResetForgotPassModel
   */
  token: string;
}

/**
 * Check if a given object implements the ResetForgotPassModel interface.
 */
export function instanceOfResetForgotPassModel(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'password' in value;
  isInstance = isInstance && 'email' in value;
  isInstance = isInstance && 'token' in value;

  return isInstance;
}

export function ResetForgotPassModelFromJSON(json: any): ResetForgotPassModel {
  return ResetForgotPassModelFromJSONTyped(json, false);
}

export function ResetForgotPassModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResetForgotPassModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    password: json['password'],
    email: json['email'],
    token: json['token'],
  };
}

export function ResetForgotPassModelToJSON(
  value?: ResetForgotPassModel | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    password: value.password,
    email: value.email,
    token: value.token,
  };
}
