/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResetPassModel
 */
export interface ResetPassModel {
  /**
   *
   * @type {string}
   * @memberof ResetPassModel
   */
  oldPassword: string;
  /**
   *
   * @type {string}
   * @memberof ResetPassModel
   */
  newPassword: string;
}

/**
 * Check if a given object implements the ResetPassModel interface.
 */
export function instanceOfResetPassModel(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'oldPassword' in value;
  isInstance = isInstance && 'newPassword' in value;

  return isInstance;
}

export function ResetPassModelFromJSON(json: any): ResetPassModel {
  return ResetPassModelFromJSONTyped(json, false);
}

export function ResetPassModelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResetPassModel {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    oldPassword: json['oldPassword'],
    newPassword: json['newPassword'],
  };
}

export function ResetPassModelToJSON(value?: ResetPassModel | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    oldPassword: value.oldPassword,
    newPassword: value.newPassword,
  };
}
