/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateMessageRequest
 */
export interface UpdateMessageRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateMessageRequest
   */
  content: string;
}

/**
 * Check if a given object implements the UpdateMessageRequest interface.
 */
export function instanceOfUpdateMessageRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'content' in value;

  return isInstance;
}

export function UpdateMessageRequestFromJSON(json: any): UpdateMessageRequest {
  return UpdateMessageRequestFromJSONTyped(json, false);
}

export function UpdateMessageRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateMessageRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    content: json['content'],
  };
}

export function UpdateMessageRequestToJSON(
  value?: UpdateMessageRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    content: value.content,
  };
}
