/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  displayName?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  status?: string | null;
}

/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
  return UpdateUserRequestFromJSONTyped(json, false);
}

export function UpdateUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    displayName: !exists(json, 'displayName') ? undefined : json['displayName'],
    status: !exists(json, 'status') ? undefined : json['status'],
  };
}

export function UpdateUserRequestToJSON(value?: UpdateUserRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    displayName: value.displayName,
    status: value.status,
  };
}
